### PR TITLE
Add deployment to debian repositories

### PR DESCRIPTION
**Pull request by igagis**
So far it only packs the binary into the debian package.

Next thing would be to think about how to automatically install the runner as `systemd` service and provide configuration scripts.

In order the deployment to my debian repo server work you will need to add `MYCI_REPO_SSH_KEY` secret to your github repo with the ssh private key. If you tell me your email, I'd send you the private key you need to put there. Or check secrets of my forked repo, github tells me you should have access.

Instructions regarding the repo added to the README.

### CODE REVIEW

**Comment by ChristopherHX** [comment]
Thank you, this seems to be a good starting point.

> Or check secrets of my forked repo, github tells me you should have access.

Secret values cannot be shown in the github settings even if I would be the owner of your fork. It might be possible for me to change your workflow to transfer your secret key home.

Isn't it better I share you a public key instead? Private keys shouldn't be send per email. I assume you should be able to add it to your server.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCn2Yvt9RvJV/qenjts5dKMls8uABbb54ZS1BIoyc0L0x82c6cG3p2RiY1D47vW1+9pPypRM7rhMA/SDJPenK5g6vr+KOa7tN1aYwSImiDSBBNkjVfR3wiWlBy41AfSDHrKWa8LiFgP/+J//mhfZhp4P2ucbETXhG+RJhiYx1egC4MKjCNYeqMeZa++eFmZHTggz/SGFF++D0e9kmtZp4lVyfxYMfKF20v0h3W3iBf9IyRtJfUSFe6mQ8IA34Y/go7fftShDFFlz7vBjThTUKuA1PUX3/09QTOtAufFr42hcDrLPBZsMJq9TaFsGKcDDZOJBlsV4kcClY0pRokVuDj6Z7oVaryAsZ47QsnZnew0w2ZhRFlNjAbQduuN3/pmuFdbEVn8aVTTpQnBzry+C/ShX1y+3g1K0alJc2c+2iH1fmKDYh5vwCeINkv/23j9CyDyxrJONcX14rQQ5aFnthG8Us+4Q88yH8sYSq1BNHhqbq538SI3iEtRRBgtwnX23iU=
```

My email is christopher.homberger@web.de

**Comment by igagis** [comment]
Ok, it is better that you share the public key, I just thought it will be easier if I just send you what to add as a secret, so you don't have to generate the key :)

By the way, I added your username on the server as `chrishx`. If you'd like another one, let me know me know now, I will change it.

**Comment by igagis** [comment]
I added your public key to the server

**Comment by ChristopherHX** [comment]
The username is fine, thanks a lot for providing an apt repository for this project.
You workflow seems to work, after I changed my github publish job to use versions inputs without a leading v.

To add an systemd service, the runner probably needs an well known config directory.
Currently the runner uses the cwd, this is problematic, because the service need to have exact the same cwd or the service fails to start.

Maybe generate the systemd file, during configure with a service flag.

**Comment by igagis** [comment]
Yes, I also thought that config must be saved in some common place. Maybe `/etc/github-act-runner/*`?
I think deb package could install the service to systemd which runs `github-act-runner` as `root` user using configs from `/etc/github-act-runner/`. The servis would be disabled right after installation. And there would also be some script installed by the deb package `/usr/bin/setup-github-act-runner.sh` which would be interactive and, when run as root, would create configs in `/etc/github-act-runner/*` and enable the service.
Then `github-act-runner` should support some CLI key `--out-dir` which would allow saving configs in specified dir:
```console
github-act-runner configure --out-dir /etc/github-act-runner --name ...
```
Something like that?

**Comment by ChristopherHX** [comment]
Good idea. For a systemd service `/etc/github-act-runner/`  it is reasonable location for the config.
Maybe `-C`, `--directory` to change the cwd via a cli switch for both configure and run instead of `--out-dir`?

_if we add a script like `/usr/bin/setup-github-act-runner.sh`, it could technically do `cd /etc/github-act-runner` before Configure._

**Comment by igagis** [comment]
And `systemd` service can also have `WorkingDirectory` set to the dir. So, maybe no new CLI options needed.
I think the setup script would create the service files, so also not necessary to install any service files from package.
So, think only clever setup script needs to be written. If you agree, that it is a right approach, I might try to do that in the near time.

**Comment by ChristopherHX** [comment]
Yes I agree a good setup script is perfect.
I have a systemd service on my raspberry pi, it was 7 days connected, but interrupted today :(.

```
[Unit]
Description=GitHub Actions Runner
After=network.target

[Service]
ExecStart=/home/ubuntu/github-actions-act-runner-test Run
User=ubuntu
WorkingDirectory=/home/ubuntu/rc
KillMode=process
KillSignal=SIGINT
TimeoutStopSec=5min

[Install]
WantedBy=multi-user.target
```
There I have had `WorkingDirectory` already set to my home.

**Pull request merged**
