### PR TITLE
remove .sh suffix

### LINKED ISSUE #23: remove .sh suffix from manager script name
as discussed here
https://github.com/ChristopherHX/github-actions-act-runner/pull/21#discussion_r671754664

it is desirable to remove the `.sh` sufix from the `github-act-runner.sh` script.
The problem here is that there is a `github-act-runner` directory along with that in the `/usr/bin` directory. So, there can be no file with the same name in the same dir.

So, then we also need to rename the `/usr/bin/github-act-runner/` directory to something else. What would be the good name for it? Maybe `/usr/bin/github-act-runner-bin/`?

### PR DESCRIPTION
**Pull request by igagis**
Fix #23

### CODE REVIEW

**Review by ChristopherHX — APPROVED** [review]
Thank you, will test this after merging

**Comment by ChristopherHX** [comment]
Hmm do you know something about this, installed the debs from the debs artifact
```
running as user 'christopher'
Try to register runner with url: https://api.github.com/actions/runner-registration
success
Failed to connect to bus: No such file or directory
```

**Comment by igagis** [comment]
Do you run as root or as user?

**Comment by igagis** [comment]
Ah, ok 😂

**Comment by igagis** [comment]
Is it Windows linux subsystem? I supposed all recent deb-based distros support systemd...

**Comment by ChristopherHX** [comment]
> Is it Windows linux subsystem

Yes it is 'Windows linux subsystem 2' on Windows 11, but something isn't working there.
Works fine on my raspberry Pi 4 - ubuntu 20.04.

**Comment by igagis** [comment]
> something isn't working there.

I have updated to v 0.0.4 and configured the runners via script on my `odroid xu4` boards.
I found that when I ssh as one user, say `ivan`, then I do `su github` to switch to `github` user and the I try to manage runners then I get the `Failed to connect to bus: Permission denied` error. But if I `ssh` as `github` user right away, then all works.
I found the same problem when generating `gpg` keys, it does not work from under `su user`. Just FYI.

But it is really great that now it works as `systemd` service and when doing `apt upgrade` it should restart the services automatically. This eases the process of deploying new version of the runner a lot! Now it is usable :). Thanks for prompt support on that!

**Pull request merged**
